// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authorization_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error) {
	ret := _mock.Called(context1, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) (entity.Authorization, error)); ok {
		return returnFunc(context1, authorization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) entity.Authorization); ok {
		r0 = returnFunc(context1, authorization)
	} else {
		r0 = ret.Get(0).(entity.Authorization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Authorization) error); ok {
		r1 = returnFunc(context1, authorization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - authorization entity.Authorization
func (_e *MockRepository_Expecter) Create(context1 interface{}, authorization interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", context1, authorization)}
}

func (_c *MockRepository_Create_Call) Run(run func(context1 context.Context, authorization entity.Authorization)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Authorization
		if args[1] != nil {
			arg1 = args[1].(entity.Authorization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(authorization1 entity.Authorization, err error) *MockRepository_Create_Call {
	_c.Call.Return(authorization1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Delete(context1 interface{}, s interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockRepository_Delete_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockRepository
func (_mock *MockRepository) Read(context1 context.Context, authorizationFilter entity.AuthorizationFilter) ([]entity.Authorization, error) {
	ret := _mock.Called(context1, authorizationFilter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.AuthorizationFilter) ([]entity.Authorization, error)); ok {
		return returnFunc(context1, authorizationFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.AuthorizationFilter) []entity.Authorization); ok {
		r0 = returnFunc(context1, authorizationFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Authorization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.AuthorizationFilter) error); ok {
		r1 = returnFunc(context1, authorizationFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - authorizationFilter entity.AuthorizationFilter
func (_e *MockRepository_Expecter) Read(context1 interface{}, authorizationFilter interface{}) *MockRepository_Read_Call {
	return &MockRepository_Read_Call{Call: _e.mock.On("Read", context1, authorizationFilter)}
}

func (_c *MockRepository_Read_Call) Run(run func(context1 context.Context, authorizationFilter entity.AuthorizationFilter)) *MockRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.AuthorizationFilter
		if args[1] != nil {
			arg1 = args[1].(entity.AuthorizationFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Read_Call) Return(authorizations []entity.Authorization, err error) *MockRepository_Read_Call {
	_c.Call.Return(authorizations, err)
	return _c
}

func (_c *MockRepository_Read_Call) RunAndReturn(run func(context1 context.Context, authorizationFilter entity.AuthorizationFilter) ([]entity.Authorization, error)) *MockRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error) {
	ret := _mock.Called(context1, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) (entity.Authorization, error)); ok {
		return returnFunc(context1, authorization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) entity.Authorization); ok {
		r0 = returnFunc(context1, authorization)
	} else {
		r0 = ret.Get(0).(entity.Authorization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Authorization) error); ok {
		r1 = returnFunc(context1, authorization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - authorization entity.Authorization
func (_e *MockRepository_Expecter) Update(context1 interface{}, authorization interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", context1, authorization)}
}

func (_c *MockRepository_Update_Call) Run(run func(context1 context.Context, authorization entity.Authorization)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Authorization
		if args[1] != nil {
			arg1 = args[1].(entity.Authorization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(authorization1 entity.Authorization, err error) *MockRepository_Update_Call {
	_c.Call.Return(authorization1, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
