// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authorization_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ActiveHolds provides a mock function for the type MockService
func (_mock *MockService) ActiveHolds(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for ActiveHolds")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ActiveHolds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveHolds'
type MockService_ActiveHolds_Call struct {
	*mock.Call
}

// ActiveHolds is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) ActiveHolds(context1 interface{}, account interface{}, day interface{}) *MockService_ActiveHolds_Call {
	return &MockService_ActiveHolds_Call{Call: _e.mock.On("ActiveHolds", context1, account, day)}
}

func (_c *MockService_ActiveHolds_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_ActiveHolds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ActiveHolds_Call) Return(money entity.Money, err error) *MockService_ActiveHolds_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_ActiveHolds_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_ActiveHolds_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockService
func (_mock *MockService) All(context1 context.Context) ([]entity.Authorization, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Authorization, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Authorization); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Authorization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockService_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockService_Expecter) All(context1 interface{}) *MockService_All_Call {
	return &MockService_All_Call{Call: _e.mock.On("All", context1)}
}

func (_c *MockService_All_Call) Run(run func(context1 context.Context)) *MockService_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_All_Call) Return(authorizations []entity.Authorization, err error) *MockService_All_Call {
	_c.Call.Return(authorizations, err)
	return _c
}

func (_c *MockService_All_Call) RunAndReturn(run func(context1 context.Context) ([]entity.Authorization, error)) *MockService_All_Call {
	_c.Call.Return(run)
	return _c
}

// Authorize provides a mock function for the type MockService
func (_mock *MockService) Authorize(context1 context.Context, account entity.Account, event entity.Event) error {
	ret := _mock.Called(context1, account, event)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) error); ok {
		r0 = returnFunc(context1, account, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
func (_e *MockService_Expecter) Authorize(context1 interface{}, account interface{}, event interface{}) *MockService_Authorize_Call {
	return &MockService_Authorize_Call{Call: _e.mock.On("Authorize", context1, account, event)}
}

func (_c *MockService_Authorize_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event)) *MockService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Authorize_Call) Return(err error) *MockService_Authorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Authorize_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event) error) *MockService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// AvailableBalance provides a mock function for the type MockService
func (_mock *MockService) AvailableBalance(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for AvailableBalance")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AvailableBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableBalance'
type MockService_AvailableBalance_Call struct {
	*mock.Call
}

// AvailableBalance is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) AvailableBalance(context1 interface{}, account interface{}, day interface{}) *MockService_AvailableBalance_Call {
	return &MockService_AvailableBalance_Call{Call: _e.mock.On("AvailableBalance", context1, account, day)}
}

func (_c *MockService_AvailableBalance_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_AvailableBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AvailableBalance_Call) Return(money entity.Money, err error) *MockService_AvailableBalance_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_AvailableBalance_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_AvailableBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Settle provides a mock function for the type MockService
func (_mock *MockService) Settle(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, account, event)

	if len(ret) == 0 {
		panic("no return value specified for Settle")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, account, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, account, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Event) error); ok {
		r1 = returnFunc(context1, account, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Settle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Settle'
type MockService_Settle_Call struct {
	*mock.Call
}

// Settle is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
func (_e *MockService_Expecter) Settle(context1 interface{}, account interface{}, event interface{}) *MockService_Settle_Call {
	return &MockService_Settle_Call{Call: _e.mock.On("Settle", context1, account, event)}
}

func (_c *MockService_Settle_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event)) *MockService_Settle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Settle_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Settle_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Settle_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error)) *MockService_Settle_Call {
	_c.Call.Return(run)
	return _c
}
