// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authorization_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ActiveHolds provides a mock function for the type MockService
func (_mock *MockService) ActiveHolds(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for ActiveHolds")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ActiveHolds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveHolds'
type MockService_ActiveHolds_Call struct {
	*mock.Call
}

// ActiveHolds is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) ActiveHolds(context1 interface{}, account interface{}, day interface{}) *MockService_ActiveHolds_Call {
	return &MockService_ActiveHolds_Call{Call: _e.mock.On("ActiveHolds", context1, account, day)}
}

func (_c *MockService_ActiveHolds_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_ActiveHolds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ActiveHolds_Call) Return(money entity.Money, err error) *MockService_ActiveHolds_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_ActiveHolds_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_ActiveHolds_Call {
	_c.Call.Return(run)
	return _c
}

// Authorize provides a mock function for the type MockService
func (_mock *MockService) Authorize(context1 context.Context, account entity.Account, event entity.Event) error {
	ret := _mock.Called(context1, account, event)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) error); ok {
		r0 = returnFunc(context1, account, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
func (_e *MockService_Expecter) Authorize(context1 interface{}, account interface{}, event interface{}) *MockService_Authorize_Call {
	return &MockService_Authorize_Call{Call: _e.mock.On("Authorize", context1, account, event)}
}

func (_c *MockService_Authorize_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event)) *MockService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Authorize_Call) Return(err error) *MockService_Authorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Authorize_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event) error) *MockService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// AvailableBalance provides a mock function for the type MockService
func (_mock *MockService) AvailableBalance(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for AvailableBalance")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AvailableBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableBalance'
type MockService_AvailableBalance_Call struct {
	*mock.Call
}

// AvailableBalance is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) AvailableBalance(context1 interface{}, account interface{}, day interface{}) *MockService_AvailableBalance_Call {
	return &MockService_AvailableBalance_Call{Call: _e.mock.On("AvailableBalance", context1, account, day)}
}

func (_c *MockService_AvailableBalance_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_AvailableBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AvailableBalance_Call) Return(money entity.Money, err error) *MockService_AvailableBalance_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_AvailableBalance_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_AvailableBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error) {
	ret := _mock.Called(context1, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) (entity.Authorization, error)); ok {
		return returnFunc(context1, authorization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) entity.Authorization); ok {
		r0 = returnFunc(context1, authorization)
	} else {
		r0 = ret.Get(0).(entity.Authorization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Authorization) error); ok {
		r1 = returnFunc(context1, authorization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - authorization entity.Authorization
func (_e *MockService_Expecter) Create(context1 interface{}, authorization interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", context1, authorization)}
}

func (_c *MockService_Create_Call) Run(run func(context1 context.Context, authorization entity.Authorization)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Authorization
		if args[1] != nil {
			arg1 = args[1].(entity.Authorization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(authorization1 entity.Authorization, err error) *MockService_Create_Call {
	_c.Call.Return(authorization1, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockService_Expecter) Delete(context1 interface{}, s interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockService_Delete_Call) Run(run func(context1 context.Context, s string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockService
func (_mock *MockService) Read(context1 context.Context, authorizationFilter entity.AuthorizationFilter) ([]entity.Authorization, error) {
	ret := _mock.Called(context1, authorizationFilter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.AuthorizationFilter) ([]entity.Authorization, error)); ok {
		return returnFunc(context1, authorizationFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.AuthorizationFilter) []entity.Authorization); ok {
		r0 = returnFunc(context1, authorizationFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Authorization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.AuthorizationFilter) error); ok {
		r1 = returnFunc(context1, authorizationFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - authorizationFilter entity.AuthorizationFilter
func (_e *MockService_Expecter) Read(context1 interface{}, authorizationFilter interface{}) *MockService_Read_Call {
	return &MockService_Read_Call{Call: _e.mock.On("Read", context1, authorizationFilter)}
}

func (_c *MockService_Read_Call) Run(run func(context1 context.Context, authorizationFilter entity.AuthorizationFilter)) *MockService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.AuthorizationFilter
		if args[1] != nil {
			arg1 = args[1].(entity.AuthorizationFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Read_Call) Return(authorizations []entity.Authorization, err error) *MockService_Read_Call {
	_c.Call.Return(authorizations, err)
	return _c
}

func (_c *MockService_Read_Call) RunAndReturn(run func(context1 context.Context, authorizationFilter entity.AuthorizationFilter) ([]entity.Authorization, error)) *MockService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Settle provides a mock function for the type MockService
func (_mock *MockService) Settle(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, account, event)

	if len(ret) == 0 {
		panic("no return value specified for Settle")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, account, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, account, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Event) error); ok {
		r1 = returnFunc(context1, account, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Settle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Settle'
type MockService_Settle_Call struct {
	*mock.Call
}

// Settle is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
func (_e *MockService_Expecter) Settle(context1 interface{}, account interface{}, event interface{}) *MockService_Settle_Call {
	return &MockService_Settle_Call{Call: _e.mock.On("Settle", context1, account, event)}
}

func (_c *MockService_Settle_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event)) *MockService_Settle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Settle_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Settle_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Settle_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error)) *MockService_Settle_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error) {
	ret := _mock.Called(context1, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Authorization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) (entity.Authorization, error)); ok {
		return returnFunc(context1, authorization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Authorization) entity.Authorization); ok {
		r0 = returnFunc(context1, authorization)
	} else {
		r0 = ret.Get(0).(entity.Authorization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Authorization) error); ok {
		r1 = returnFunc(context1, authorization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - authorization entity.Authorization
func (_e *MockService_Expecter) Update(context1 interface{}, authorization interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", context1, authorization)}
}

func (_c *MockService_Update_Call) Run(run func(context1 context.Context, authorization entity.Authorization)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Authorization
		if args[1] != nil {
			arg1 = args[1].(entity.Authorization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(authorization1 entity.Authorization, err error) *MockService_Update_Call {
	_c.Call.Return(authorization1, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context1 context.Context, authorization entity.Authorization) (entity.Authorization, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
