// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interest_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Accruals provides a mock function for the type MockRepository
func (_mock *MockRepository) Accruals(context1 context.Context) ([]entity.Accrual, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Accruals")
	}

	var r0 []entity.Accrual
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Accrual, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Accrual); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Accrual)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Accruals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accruals'
type MockRepository_Accruals_Call struct {
	*mock.Call
}

// Accruals is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Accruals(context1 interface{}) *MockRepository_Accruals_Call {
	return &MockRepository_Accruals_Call{Call: _e.mock.On("Accruals", context1)}
}

func (_c *MockRepository_Accruals_Call) Run(run func(context1 context.Context)) *MockRepository_Accruals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Accruals_Call) Return(accruals []entity.Accrual, err error) *MockRepository_Accruals_Call {
	_c.Call.Return(accruals, err)
	return _c
}

func (_c *MockRepository_Accruals_Call) RunAndReturn(run func(context1 context.Context) ([]entity.Accrual, error)) *MockRepository_Accruals_Call {
	_c.Call.Return(run)
	return _c
}

// AppendAccrual provides a mock function for the type MockRepository
func (_mock *MockRepository) AppendAccrual(context1 context.Context, accrual entity.Accrual) (entity.Accrual, error) {
	ret := _mock.Called(context1, accrual)

	if len(ret) == 0 {
		panic("no return value specified for AppendAccrual")
	}

	var r0 entity.Accrual
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Accrual) (entity.Accrual, error)); ok {
		return returnFunc(context1, accrual)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Accrual) entity.Accrual); ok {
		r0 = returnFunc(context1, accrual)
	} else {
		r0 = ret.Get(0).(entity.Accrual)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Accrual) error); ok {
		r1 = returnFunc(context1, accrual)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AppendAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendAccrual'
type MockRepository_AppendAccrual_Call struct {
	*mock.Call
}

// AppendAccrual is a helper method to define mock.On call
//   - context1 context.Context
//   - accrual entity.Accrual
func (_e *MockRepository_Expecter) AppendAccrual(context1 interface{}, accrual interface{}) *MockRepository_AppendAccrual_Call {
	return &MockRepository_AppendAccrual_Call{Call: _e.mock.On("AppendAccrual", context1, accrual)}
}

func (_c *MockRepository_AppendAccrual_Call) Run(run func(context1 context.Context, accrual entity.Accrual)) *MockRepository_AppendAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Accrual
		if args[1] != nil {
			arg1 = args[1].(entity.Accrual)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AppendAccrual_Call) Return(accrual1 entity.Accrual, err error) *MockRepository_AppendAccrual_Call {
	_c.Call.Return(accrual1, err)
	return _c
}

func (_c *MockRepository_AppendAccrual_Call) RunAndReturn(run func(context1 context.Context, accrual entity.Accrual) (entity.Accrual, error)) *MockRepository_AppendAccrual_Call {
	_c.Call.Return(run)
	return _c
}
