// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interest_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Accruals provides a mock function for the type MockService
func (_mock *MockService) Accruals(context1 context.Context) ([]entity.Accrual, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Accruals")
	}

	var r0 []entity.Accrual
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Accrual, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Accrual); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Accrual)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Accruals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accruals'
type MockService_Accruals_Call struct {
	*mock.Call
}

// Accruals is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockService_Expecter) Accruals(context1 interface{}) *MockService_Accruals_Call {
	return &MockService_Accruals_Call{Call: _e.mock.On("Accruals", context1)}
}

func (_c *MockService_Accruals_Call) Run(run func(context1 context.Context)) *MockService_Accruals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Accruals_Call) Return(accruals []entity.Accrual, err error) *MockService_Accruals_Call {
	_c.Call.Return(accruals, err)
	return _c
}

func (_c *MockService_Accruals_Call) RunAndReturn(run func(context1 context.Context) ([]entity.Accrual, error)) *MockService_Accruals_Call {
	_c.Call.Return(run)
	return _c
}

// Accrue provides a mock function for the type MockService
func (_mock *MockService) Accrue(context1 context.Context, account entity.Account, day entity.Day) error {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for Accrue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) error); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Accrue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accrue'
type MockService_Accrue_Call struct {
	*mock.Call
}

// Accrue is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) Accrue(context1 interface{}, account interface{}, day interface{}) *MockService_Accrue_Call {
	return &MockService_Accrue_Call{Call: _e.mock.On("Accrue", context1, account, day)}
}

func (_c *MockService_Accrue_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_Accrue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Accrue_Call) Return(err error) *MockService_Accrue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Accrue_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) error) *MockService_Accrue_Call {
	_c.Call.Return(run)
	return _c
}

// Capitalise provides a mock function for the type MockService
func (_mock *MockService) Capitalise(context1 context.Context, account entity.Account, day entity.Day) error {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for Capitalise")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) error); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Capitalise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capitalise'
type MockService_Capitalise_Call struct {
	*mock.Call
}

// Capitalise is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) Capitalise(context1 interface{}, account interface{}, day interface{}) *MockService_Capitalise_Call {
	return &MockService_Capitalise_Call{Call: _e.mock.On("Capitalise", context1, account, day)}
}

func (_c *MockService_Capitalise_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_Capitalise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Capitalise_Call) Return(err error) *MockService_Capitalise_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Capitalise_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) error) *MockService_Capitalise_Call {
	_c.Call.Return(run)
	return _c
}

// NetAccrual provides a mock function for the type MockService
func (_mock *MockService) NetAccrual(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for NetAccrual")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NetAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetAccrual'
type MockService_NetAccrual_Call struct {
	*mock.Call
}

// NetAccrual is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) NetAccrual(context1 interface{}, account interface{}, day interface{}) *MockService_NetAccrual_Call {
	return &MockService_NetAccrual_Call{Call: _e.mock.On("NetAccrual", context1, account, day)}
}

func (_c *MockService_NetAccrual_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_NetAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NetAccrual_Call) Return(money entity.Money, err error) *MockService_NetAccrual_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_NetAccrual_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_NetAccrual_Call {
	_c.Call.Return(run)
	return _c
}
