// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fee_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockRepository
func (_mock *MockRepository) Clear(context1 context.Context, s string, day entity.Day) error {
	ret := _mock.Called(context1, s, day)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Day) error); ok {
		r0 = returnFunc(context1, s, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - day entity.Day
func (_e *MockRepository_Expecter) Clear(context1 interface{}, s interface{}, day interface{}) *MockRepository_Clear_Call {
	return &MockRepository_Clear_Call{Call: _e.mock.On("Clear", context1, s, day)}
}

func (_c *MockRepository_Clear_Call) Run(run func(context1 context.Context, s string, day entity.Day)) *MockRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Clear_Call) Return(err error) *MockRepository_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Clear_Call) RunAndReturn(run func(context1 context.Context, s string, day entity.Day) error) *MockRepository_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// IsAssessed provides a mock function for the type MockRepository
func (_mock *MockRepository) IsAssessed(context1 context.Context, s string, day entity.Day) (bool, error) {
	ret := _mock.Called(context1, s, day)

	if len(ret) == 0 {
		panic("no return value specified for IsAssessed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Day) (bool, error)); ok {
		return returnFunc(context1, s, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Day) bool); ok {
		r0 = returnFunc(context1, s, day)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.Day) error); ok {
		r1 = returnFunc(context1, s, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IsAssessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAssessed'
type MockRepository_IsAssessed_Call struct {
	*mock.Call
}

// IsAssessed is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - day entity.Day
func (_e *MockRepository_Expecter) IsAssessed(context1 interface{}, s interface{}, day interface{}) *MockRepository_IsAssessed_Call {
	return &MockRepository_IsAssessed_Call{Call: _e.mock.On("IsAssessed", context1, s, day)}
}

func (_c *MockRepository_IsAssessed_Call) Run(run func(context1 context.Context, s string, day entity.Day)) *MockRepository_IsAssessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_IsAssessed_Call) Return(b bool, err error) *MockRepository_IsAssessed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_IsAssessed_Call) RunAndReturn(run func(context1 context.Context, s string, day entity.Day) (bool, error)) *MockRepository_IsAssessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAssessed provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkAssessed(context1 context.Context, s string, day entity.Day) error {
	ret := _mock.Called(context1, s, day)

	if len(ret) == 0 {
		panic("no return value specified for MarkAssessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.Day) error); ok {
		r0 = returnFunc(context1, s, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkAssessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAssessed'
type MockRepository_MarkAssessed_Call struct {
	*mock.Call
}

// MarkAssessed is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - day entity.Day
func (_e *MockRepository_Expecter) MarkAssessed(context1 interface{}, s interface{}, day interface{}) *MockRepository_MarkAssessed_Call {
	return &MockRepository_MarkAssessed_Call{Call: _e.mock.On("MarkAssessed", context1, s, day)}
}

func (_c *MockRepository_MarkAssessed_Call) Run(run func(context1 context.Context, s string, day entity.Day)) *MockRepository_MarkAssessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkAssessed_Call) Return(err error) *MockRepository_MarkAssessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkAssessed_Call) RunAndReturn(run func(context1 context.Context, s string, day entity.Day) error) *MockRepository_MarkAssessed_Call {
	_c.Call.Return(run)
	return _c
}
