// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fee_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Assess provides a mock function for the type MockService
func (_mock *MockService) Assess(context1 context.Context, account entity.Account, day entity.Day) error {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for Assess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) error); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Assess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assess'
type MockService_Assess_Call struct {
	*mock.Call
}

// Assess is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) Assess(context1 interface{}, account interface{}, day interface{}) *MockService_Assess_Call {
	return &MockService_Assess_Call{Call: _e.mock.On("Assess", context1, account, day)}
}

func (_c *MockService_Assess_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_Assess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Assess_Call) Return(err error) *MockService_Assess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Assess_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) error) *MockService_Assess_Call {
	_c.Call.Return(run)
	return _c
}

// ReverseOnCauseReversal provides a mock function for the type MockService
func (_mock *MockService) ReverseOnCauseReversal(context1 context.Context, account entity.Account, day entity.Day) error {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for ReverseOnCauseReversal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) error); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ReverseOnCauseReversal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReverseOnCauseReversal'
type MockService_ReverseOnCauseReversal_Call struct {
	*mock.Call
}

// ReverseOnCauseReversal is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) ReverseOnCauseReversal(context1 interface{}, account interface{}, day interface{}) *MockService_ReverseOnCauseReversal_Call {
	return &MockService_ReverseOnCauseReversal_Call{Call: _e.mock.On("ReverseOnCauseReversal", context1, account, day)}
}

func (_c *MockService_ReverseOnCauseReversal_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_ReverseOnCauseReversal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ReverseOnCauseReversal_Call) Return(err error) *MockService_ReverseOnCauseReversal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ReverseOnCauseReversal_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) error) *MockService_ReverseOnCauseReversal_Call {
	_c.Call.Return(run)
	return _c
}
