// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package replay_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Events provides a mock function for the type MockRepository
func (_mock *MockRepository) Events(context1 context.Context) ([]entity.Event, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []entity.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Event, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Event); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockRepository_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Events(context1 interface{}) *MockRepository_Events_Call {
	return &MockRepository_Events_Call{Call: _e.mock.On("Events", context1)}
}

func (_c *MockRepository_Events_Call) Run(run func(context1 context.Context)) *MockRepository_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Events_Call) Return(events []entity.Event, err error) *MockRepository_Events_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockRepository_Events_Call) RunAndReturn(run func(context1 context.Context) ([]entity.Event, error)) *MockRepository_Events_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockRepository
func (_mock *MockRepository) Load(context1 context.Context, events []entity.Event) error {
	ret := _mock.Called(context1, events)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Event) error); ok {
		r0 = returnFunc(context1, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - events []entity.Event
func (_e *MockRepository_Expecter) Load(context1 interface{}, events interface{}) *MockRepository_Load_Call {
	return &MockRepository_Load_Call{Call: _e.mock.On("Load", context1, events)}
}

func (_c *MockRepository_Load_Call) Run(run func(context1 context.Context, events []entity.Event)) *MockRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Event
		if args[1] != nil {
			arg1 = args[1].([]entity.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Load_Call) Return(err error) *MockRepository_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Load_Call) RunAndReturn(run func(context1 context.Context, events []entity.Event) error) *MockRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}
