// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package replay_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	"github.com/ericmarcelinotju/mal-assessment/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CloseDay provides a mock function for the type MockService
func (_mock *MockService) CloseDay(context1 context.Context, day entity.Day) error {
	ret := _mock.Called(context1, day)

	if len(ret) == 0 {
		panic("no return value specified for CloseDay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Day) error); ok {
		r0 = returnFunc(context1, day)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CloseDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDay'
type MockService_CloseDay_Call struct {
	*mock.Call
}

// CloseDay is a helper method to define mock.On call
//   - context1 context.Context
//   - day entity.Day
func (_e *MockService_Expecter) CloseDay(context1 interface{}, day interface{}) *MockService_CloseDay_Call {
	return &MockService_CloseDay_Call{Call: _e.mock.On("CloseDay", context1, day)}
}

func (_c *MockService_CloseDay_Call) Run(run func(context1 context.Context, day entity.Day)) *MockService_CloseDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Day
		if args[1] != nil {
			arg1 = args[1].(entity.Day)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CloseDay_Call) Return(err error) *MockService_CloseDay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CloseDay_Call) RunAndReturn(run func(context1 context.Context, day entity.Day) error) *MockService_CloseDay_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockService
func (_mock *MockService) Config() config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Config
	if returnFunc, ok := ret.Get(0).(func() config.Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.Config)
	}
	return r0
}

// MockService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockService_Expecter) Config() *MockService_Config_Call {
	return &MockService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockService_Config_Call) Run(run func()) *MockService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Config_Call) Return(config1 config.Config) *MockService_Config_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockService_Config_Call) RunAndReturn(run func() config.Config) *MockService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockService
func (_mock *MockService) Post(context1 context.Context, event entity.Event) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, event)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Event) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Event) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Event) error); ok {
		r1 = returnFunc(context1, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockService_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - context1 context.Context
//   - event entity.Event
func (_e *MockService_Expecter) Post(context1 interface{}, event interface{}) *MockService_Post_Call {
	return &MockService_Post_Call{Call: _e.mock.On("Post", context1, event)}
}

func (_c *MockService_Post_Call) Run(run func(context1 context.Context, event entity.Event)) *MockService_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Event
		if args[1] != nil {
			arg1 = args[1].(entity.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Post_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Post_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Post_Call) RunAndReturn(run func(context1 context.Context, event entity.Event) ([]entity.LedgerEntry, error)) *MockService_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function for the type MockService
func (_mock *MockService) Report(context1 context.Context) ([]entity.DayReport, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 []entity.DayReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.DayReport, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.DayReport); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.DayReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockService_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockService_Expecter) Report(context1 interface{}) *MockService_Report_Call {
	return &MockService_Report_Call{Call: _e.mock.On("Report", context1)}
}

func (_c *MockService_Report_Call) Run(run func(context1 context.Context)) *MockService_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Report_Call) Return(dayReports []entity.DayReport, err error) *MockService_Report_Call {
	_c.Call.Return(dayReports, err)
	return _c
}

func (_c *MockService_Report_Call) RunAndReturn(run func(context1 context.Context) ([]entity.DayReport, error)) *MockService_Report_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockService
func (_mock *MockService) Run(context1 context.Context, events []entity.Event) error {
	ret := _mock.Called(context1, events)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Event) error); ok {
		r0 = returnFunc(context1, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockService_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - events []entity.Event
func (_e *MockService_Expecter) Run(context1 interface{}, events interface{}) *MockService_Run_Call {
	return &MockService_Run_Call{Call: _e.mock.On("Run", context1, events)}
}

func (_c *MockService_Run_Call) Run(run func(context1 context.Context, events []entity.Event)) *MockService_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Event
		if args[1] != nil {
			arg1 = args[1].([]entity.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Run_Call) Return(err error) *MockService_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Run_Call) RunAndReturn(run func(context1 context.Context, events []entity.Event) error) *MockService_Run_Call {
	_c.Call.Return(run)
	return _c
}
