// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ledger_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AppendEntry provides a mock function for the type MockRepository
func (_mock *MockRepository) AppendEntry(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error) {
	ret := _mock.Called(context1, ledgerEntry)

	if len(ret) == 0 {
		panic("no return value specified for AppendEntry")
	}

	var r0 entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) (entity.LedgerEntry, error)); ok {
		return returnFunc(context1, ledgerEntry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) entity.LedgerEntry); ok {
		r0 = returnFunc(context1, ledgerEntry)
	} else {
		r0 = ret.Get(0).(entity.LedgerEntry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.LedgerEntry) error); ok {
		r1 = returnFunc(context1, ledgerEntry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AppendEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEntry'
type MockRepository_AppendEntry_Call struct {
	*mock.Call
}

// AppendEntry is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerEntry entity.LedgerEntry
func (_e *MockRepository_Expecter) AppendEntry(context1 interface{}, ledgerEntry interface{}) *MockRepository_AppendEntry_Call {
	return &MockRepository_AppendEntry_Call{Call: _e.mock.On("AppendEntry", context1, ledgerEntry)}
}

func (_c *MockRepository_AppendEntry_Call) Run(run func(context1 context.Context, ledgerEntry entity.LedgerEntry)) *MockRepository_AppendEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerEntry
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AppendEntry_Call) Return(ledgerEntry1 entity.LedgerEntry, err error) *MockRepository_AppendEntry_Call {
	_c.Call.Return(ledgerEntry1, err)
	return _c
}

func (_c *MockRepository_AppendEntry_Call) RunAndReturn(run func(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error)) *MockRepository_AppendEntry_Call {
	_c.Call.Return(run)
	return _c
}

// AppendError provides a mock function for the type MockRepository
func (_mock *MockRepository) AppendError(context1 context.Context, ledgerError entity.LedgerError) error {
	ret := _mock.Called(context1, ledgerError)

	if len(ret) == 0 {
		panic("no return value specified for AppendError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerError) error); ok {
		r0 = returnFunc(context1, ledgerError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AppendError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendError'
type MockRepository_AppendError_Call struct {
	*mock.Call
}

// AppendError is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerError entity.LedgerError
func (_e *MockRepository_Expecter) AppendError(context1 interface{}, ledgerError interface{}) *MockRepository_AppendError_Call {
	return &MockRepository_AppendError_Call{Call: _e.mock.On("AppendError", context1, ledgerError)}
}

func (_c *MockRepository_AppendError_Call) Run(run func(context1 context.Context, ledgerError entity.LedgerError)) *MockRepository_AppendError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerError
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerError)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AppendError_Call) Return(err error) *MockRepository_AppendError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AppendError_Call) RunAndReturn(run func(context1 context.Context, ledgerError entity.LedgerError) error) *MockRepository_AppendError_Call {
	_c.Call.Return(run)
	return _c
}

// Entries provides a mock function for the type MockRepository
func (_mock *MockRepository) Entries(context1 context.Context) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Entries")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Entries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entries'
type MockRepository_Entries_Call struct {
	*mock.Call
}

// Entries is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Entries(context1 interface{}) *MockRepository_Entries_Call {
	return &MockRepository_Entries_Call{Call: _e.mock.On("Entries", context1)}
}

func (_c *MockRepository_Entries_Call) Run(run func(context1 context.Context)) *MockRepository_Entries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Entries_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockRepository_Entries_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockRepository_Entries_Call) RunAndReturn(run func(context1 context.Context) ([]entity.LedgerEntry, error)) *MockRepository_Entries_Call {
	_c.Call.Return(run)
	return _c
}

// Errors provides a mock function for the type MockRepository
func (_mock *MockRepository) Errors(context1 context.Context) ([]entity.LedgerError, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 []entity.LedgerError
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.LedgerError, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.LedgerError); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerError)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockRepository_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Errors(context1 interface{}) *MockRepository_Errors_Call {
	return &MockRepository_Errors_Call{Call: _e.mock.On("Errors", context1)}
}

func (_c *MockRepository_Errors_Call) Run(run func(context1 context.Context)) *MockRepository_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Errors_Call) Return(ledgerErrors []entity.LedgerError, err error) *MockRepository_Errors_Call {
	_c.Call.Return(ledgerErrors, err)
	return _c
}

func (_c *MockRepository_Errors_Call) RunAndReturn(run func(context1 context.Context) ([]entity.LedgerError, error)) *MockRepository_Errors_Call {
	_c.Call.Return(run)
	return _c
}
