// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ledger_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error) {
	ret := _mock.Called(context1, ledgerEntry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) (entity.LedgerEntry, error)); ok {
		return returnFunc(context1, ledgerEntry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) entity.LedgerEntry); ok {
		r0 = returnFunc(context1, ledgerEntry)
	} else {
		r0 = ret.Get(0).(entity.LedgerEntry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.LedgerEntry) error); ok {
		r1 = returnFunc(context1, ledgerEntry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerEntry entity.LedgerEntry
func (_e *MockRepository_Expecter) Create(context1 interface{}, ledgerEntry interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", context1, ledgerEntry)}
}

func (_c *MockRepository_Create_Call) Run(run func(context1 context.Context, ledgerEntry entity.LedgerEntry)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerEntry
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(ledgerEntry1 entity.LedgerEntry, err error) *MockRepository_Create_Call {
	_c.Call.Return(ledgerEntry1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockRepository
func (_mock *MockRepository) Read(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, ledgerEntryFilter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntryFilter) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, ledgerEntryFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntryFilter) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, ledgerEntryFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.LedgerEntryFilter) error); ok {
		r1 = returnFunc(context1, ledgerEntryFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerEntryFilter entity.LedgerEntryFilter
func (_e *MockRepository_Expecter) Read(context1 interface{}, ledgerEntryFilter interface{}) *MockRepository_Read_Call {
	return &MockRepository_Read_Call{Call: _e.mock.On("Read", context1, ledgerEntryFilter)}
}

func (_c *MockRepository_Read_Call) Run(run func(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter)) *MockRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerEntryFilter
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerEntryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Read_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockRepository_Read_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockRepository_Read_Call) RunAndReturn(run func(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter) ([]entity.LedgerEntry, error)) *MockRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}
