// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ledger_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ClosingBalance provides a mock function for the type MockService
func (_mock *MockService) ClosingBalance(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error) {
	ret := _mock.Called(context1, account, day)

	if len(ret) == 0 {
		panic("no return value specified for ClosingBalance")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) (entity.Money, error)); ok {
		return returnFunc(context1, account, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day) entity.Money); ok {
		r0 = returnFunc(context1, account, day)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day) error); ok {
		r1 = returnFunc(context1, account, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ClosingBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosingBalance'
type MockService_ClosingBalance_Call struct {
	*mock.Call
}

// ClosingBalance is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
func (_e *MockService_Expecter) ClosingBalance(context1 interface{}, account interface{}, day interface{}) *MockService_ClosingBalance_Call {
	return &MockService_ClosingBalance_Call{Call: _e.mock.On("ClosingBalance", context1, account, day)}
}

func (_c *MockService_ClosingBalance_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day)) *MockService_ClosingBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ClosingBalance_Call) Return(money entity.Money, err error) *MockService_ClosingBalance_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_ClosingBalance_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day) (entity.Money, error)) *MockService_ClosingBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ClosingBalanceExcluding provides a mock function for the type MockService
func (_mock *MockService) ClosingBalanceExcluding(context1 context.Context, account entity.Account, day entity.Day, n int) (entity.Money, error) {
	ret := _mock.Called(context1, account, day, n)

	if len(ret) == 0 {
		panic("no return value specified for ClosingBalanceExcluding")
	}

	var r0 entity.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day, int) (entity.Money, error)); ok {
		return returnFunc(context1, account, day, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Day, int) entity.Money); ok {
		r0 = returnFunc(context1, account, day, n)
	} else {
		r0 = ret.Get(0).(entity.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Day, int) error); ok {
		r1 = returnFunc(context1, account, day, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ClosingBalanceExcluding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosingBalanceExcluding'
type MockService_ClosingBalanceExcluding_Call struct {
	*mock.Call
}

// ClosingBalanceExcluding is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - day entity.Day
//   - n int
func (_e *MockService_Expecter) ClosingBalanceExcluding(context1 interface{}, account interface{}, day interface{}, n interface{}) *MockService_ClosingBalanceExcluding_Call {
	return &MockService_ClosingBalanceExcluding_Call{Call: _e.mock.On("ClosingBalanceExcluding", context1, account, day, n)}
}

func (_c *MockService_ClosingBalanceExcluding_Call) Run(run func(context1 context.Context, account entity.Account, day entity.Day, n int)) *MockService_ClosingBalanceExcluding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Day
		if args[2] != nil {
			arg2 = args[2].(entity.Day)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ClosingBalanceExcluding_Call) Return(money entity.Money, err error) *MockService_ClosingBalanceExcluding_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_ClosingBalanceExcluding_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, day entity.Day, n int) (entity.Money, error)) *MockService_ClosingBalanceExcluding_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error) {
	ret := _mock.Called(context1, ledgerEntry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) (entity.LedgerEntry, error)); ok {
		return returnFunc(context1, ledgerEntry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntry) entity.LedgerEntry); ok {
		r0 = returnFunc(context1, ledgerEntry)
	} else {
		r0 = ret.Get(0).(entity.LedgerEntry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.LedgerEntry) error); ok {
		r1 = returnFunc(context1, ledgerEntry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerEntry entity.LedgerEntry
func (_e *MockService_Expecter) Create(context1 interface{}, ledgerEntry interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", context1, ledgerEntry)}
}

func (_c *MockService_Create_Call) Run(run func(context1 context.Context, ledgerEntry entity.LedgerEntry)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerEntry
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(ledgerEntry1 entity.LedgerEntry, err error) *MockService_Create_Call {
	_c.Call.Return(ledgerEntry1, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context1 context.Context, ledgerEntry entity.LedgerEntry) (entity.LedgerEntry, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockService
func (_mock *MockService) Post(context1 context.Context, account entity.Account, event entity.Event, money entity.Money, entryOrigin entity.EntryOrigin) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, account, event, money, entryOrigin)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event, entity.Money, entity.EntryOrigin) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, account, event, money, entryOrigin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event, entity.Money, entity.EntryOrigin) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, account, event, money, entryOrigin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Event, entity.Money, entity.EntryOrigin) error); ok {
		r1 = returnFunc(context1, account, event, money, entryOrigin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockService_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
//   - money entity.Money
//   - entryOrigin entity.EntryOrigin
func (_e *MockService_Expecter) Post(context1 interface{}, account interface{}, event interface{}, money interface{}, entryOrigin interface{}) *MockService_Post_Call {
	return &MockService_Post_Call{Call: _e.mock.On("Post", context1, account, event, money, entryOrigin)}
}

func (_c *MockService_Post_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event, money entity.Money, entryOrigin entity.EntryOrigin)) *MockService_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		var arg3 entity.Money
		if args[3] != nil {
			arg3 = args[3].(entity.Money)
		}
		var arg4 entity.EntryOrigin
		if args[4] != nil {
			arg4 = args[4].(entity.EntryOrigin)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Post_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Post_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Post_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event, money entity.Money, entryOrigin entity.EntryOrigin) ([]entity.LedgerEntry, error)) *MockService_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockService
func (_mock *MockService) Read(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, ledgerEntryFilter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntryFilter) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, ledgerEntryFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LedgerEntryFilter) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, ledgerEntryFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.LedgerEntryFilter) error); ok {
		r1 = returnFunc(context1, ledgerEntryFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - ledgerEntryFilter entity.LedgerEntryFilter
func (_e *MockService_Expecter) Read(context1 interface{}, ledgerEntryFilter interface{}) *MockService_Read_Call {
	return &MockService_Read_Call{Call: _e.mock.On("Read", context1, ledgerEntryFilter)}
}

func (_c *MockService_Read_Call) Run(run func(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter)) *MockService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LedgerEntryFilter
		if args[1] != nil {
			arg1 = args[1].(entity.LedgerEntryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Read_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Read_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Read_Call) RunAndReturn(run func(context1 context.Context, ledgerEntryFilter entity.LedgerEntryFilter) ([]entity.LedgerEntry, error)) *MockService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Reverse provides a mock function for the type MockService
func (_mock *MockService) Reverse(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error) {
	ret := _mock.Called(context1, account, event)

	if len(ret) == 0 {
		panic("no return value specified for Reverse")
	}

	var r0 []entity.LedgerEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) ([]entity.LedgerEntry, error)); ok {
		return returnFunc(context1, account, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Account, entity.Event) []entity.LedgerEntry); ok {
		r0 = returnFunc(context1, account, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Account, entity.Event) error); ok {
		r1 = returnFunc(context1, account, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Reverse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reverse'
type MockService_Reverse_Call struct {
	*mock.Call
}

// Reverse is a helper method to define mock.On call
//   - context1 context.Context
//   - account entity.Account
//   - event entity.Event
func (_e *MockService_Expecter) Reverse(context1 interface{}, account interface{}, event interface{}) *MockService_Reverse_Call {
	return &MockService_Reverse_Call{Call: _e.mock.On("Reverse", context1, account, event)}
}

func (_c *MockService_Reverse_Call) Run(run func(context1 context.Context, account entity.Account, event entity.Event)) *MockService_Reverse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Account
		if args[1] != nil {
			arg1 = args[1].(entity.Account)
		}
		var arg2 entity.Event
		if args[2] != nil {
			arg2 = args[2].(entity.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Reverse_Call) Return(ledgerEntrys []entity.LedgerEntry, err error) *MockService_Reverse_Call {
	_c.Call.Return(ledgerEntrys, err)
	return _c
}

func (_c *MockService_Reverse_Call) RunAndReturn(run func(context1 context.Context, account entity.Account, event entity.Event) ([]entity.LedgerEntry, error)) *MockService_Reverse_Call {
	_c.Call.Return(run)
	return _c
}
