// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rejection_mock

import (
	"context"

	"github.com/ericmarcelinotju/mal-assessment/app/entity"
	"github.com/ericmarcelinotju/mal-assessment/apperror"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(context1 context.Context, event entity.Event, errorCode apperror.ErrorCode, s string) error {
	ret := _mock.Called(context1, event, errorCode, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Event, apperror.ErrorCode, string) error); ok {
		r0 = returnFunc(context1, event, errorCode, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - event entity.Event
//   - errorCode apperror.ErrorCode
//   - s string
func (_e *MockService_Expecter) Create(context1 interface{}, event interface{}, errorCode interface{}, s interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", context1, event, errorCode, s)}
}

func (_c *MockService_Create_Call) Run(run func(context1 context.Context, event entity.Event, errorCode apperror.ErrorCode, s string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Event
		if args[1] != nil {
			arg1 = args[1].(entity.Event)
		}
		var arg2 apperror.ErrorCode
		if args[2] != nil {
			arg2 = args[2].(apperror.ErrorCode)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context1 context.Context, event entity.Event, errorCode apperror.ErrorCode, s string) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockService
func (_mock *MockService) Read(context1 context.Context, rejectionFilter entity.RejectionFilter) ([]entity.LedgerError, error) {
	ret := _mock.Called(context1, rejectionFilter)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.LedgerError
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RejectionFilter) ([]entity.LedgerError, error)); ok {
		return returnFunc(context1, rejectionFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RejectionFilter) []entity.LedgerError); ok {
		r0 = returnFunc(context1, rejectionFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.LedgerError)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.RejectionFilter) error); ok {
		r1 = returnFunc(context1, rejectionFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - rejectionFilter entity.RejectionFilter
func (_e *MockService_Expecter) Read(context1 interface{}, rejectionFilter interface{}) *MockService_Read_Call {
	return &MockService_Read_Call{Call: _e.mock.On("Read", context1, rejectionFilter)}
}

func (_c *MockService_Read_Call) Run(run func(context1 context.Context, rejectionFilter entity.RejectionFilter)) *MockService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.RejectionFilter
		if args[1] != nil {
			arg1 = args[1].(entity.RejectionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Read_Call) Return(ledgerErrors []entity.LedgerError, err error) *MockService_Read_Call {
	_c.Call.Return(ledgerErrors, err)
	return _c
}

func (_c *MockService_Read_Call) RunAndReturn(run func(context1 context.Context, rejectionFilter entity.RejectionFilter) ([]entity.LedgerError, error)) *MockService_Read_Call {
	_c.Call.Return(run)
	return _c
}
